### ISSUE TITLE
run time error

### ISSUE THREAD

**Issue by daddygongon** [daddygongon/ornb#1]
> ornb
/Users/bob/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ornb (LoadError)
	from /Users/bob/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/bob/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/ornb-0.1.0/exe/ornb:5:in `<top (required)>'
	from /Users/bob/.rbenv/versions/2.4.3/bin/ornb:23:in `load'
	from /Users/bob/.rbenv/versions/2.4.3/bin/ornb:23:in `<main>'

となって動きません．lib/ornb.rbがなくなっているがどうした？

**Comment by daddygongon** [comment]
動くように修正しました．さらに，
 rewrite exe/ornb (97%)
 copy exe/ornb => lib/ornb/ornb_thor.rb (96%)
しました．これでいい感じのfile配置になってきています．templateの置き場がわかったら教えてください．
